### ISSUE TITLE
Trouble with proceeding .wfn files

### ISSUE THREAD

**Issue by mminzar** [aoterodelaroza/nciplot#10]
Hello,

I am a PhD student and I've tried to use nciplot for my systems.
I have managed to solve test cases with nciplot, however, when I tried it for my own cases it didn't work.

It gave me the Error: "At line 187 of file reader.f90 (unit = 10, file = 'pti2codchi3.wfn')
Fortran runtime error: Bad value during floating point read
Error termination. Backtrace:
Could not print backtrace: libbacktrace could not find executable to open".

I assume the problem may be is in the .wfn file, however, my .wfn input file looks similar to the example one ( the only difference is I have "The total energy" in the last line of my .wfn file and test case has "The HF Energy", so I am very confused about what is wrong and how can I fix that issue.
I have generated my .wfn files in Gaussian ( with these input lines:

"%NProcShared=24
%Chk=i2.chk
%mem=30GB
#p PBE1PBE/gen EmpiricalDispersion=GD3 pseudo=read scfcyc=1000 pop=(full,NBO) 
Output=WFN geom=check guess=check"

Can you please give me a hint of what shall I do to overcome this problem?
With the hope for your help,
Here are my input files for last calculation.
[https://drive.google.com/file/d/1wypAL8zrcKETJCNoYJvGW_US0ecTb-IQ/view?usp=sharing
](url)
[https://drive.google.com/file/d/1CNjbDWzHDW1uNPVkRaH1uV5isw-I1yy9/view?usp=sharing
](url)
[https://drive.google.com/file/d/1c7s95HyljVxPPG3J3xYqB0AF1b_6zURF/view?usp=sharing](url)

Margarita

**Comment by aoterodelaroza** [comment]
Hi Margarita,

The problem is probably in the wfn reader. However, I do not provide support or fix bugs in the nciplot code (in fact, the repo is here at someone else's request). As an alternative, you can try [critic2](https://github.com/aoterodelaroza/critic2) (the manual and installation instructions are [here](https://aoterodelaroza.github.io/critic2/)), which contains all the functionality of nciplot and does very many other things besides. Your wfn file seems to work with critic2, using this input:
~~~
molecule pti2cod-chi3-1-4-def2-TZVP.wfn 1                                       
load pti2cod-chi3-1-4-def2-TZVP.wfn                                             
nciplot                                                                         
 nstep 100 100 100                                                              
endnciplot
~~~
so this bug you found has probably been fixed at some point in the past, but only in critic2.

**Comment by mminzar** [comment]
Thank you very much for your help and a very fast response!
Sorry, I'm new to GitHub, and only my despair has brought me here, so I didn't know I'm asking in the wrong repo. 
Will try to use this critic, thank you!

**Comment by aoterodelaroza** [comment]
No worries at all! Let me know if I can help with anything else.
